#!/bin/bash
echo '// generated by:'
echo '// ./scripts/get_syscall_params.sh > pkg/straceback/syscall_params.go'
echo
echo 'package straceback'
echo
echo 'func gatherSyscallsStatic() error {'
echo '	cSyscalls = make(map[string]Syscall)'
echo
echo '	var err error'
echo '	var name string'
echo '	var cSyscall *Syscall'
echo ''
sudo find /sys/kernel/debug/tracing/events/syscalls/ -name 'sys_enter_*' -type d | \
cut --characters=53- | \
while read name ; do
  echo "	name = relateSyscallName(\"${name}\")"
  echo -n "	cSyscall, err = parseSyscall(name, string(\`"
  sudo cat /sys/kernel/debug/tracing/events/syscalls/sys_enter_${name}/format
  echo "\`))"
  echo "	if err != nil {"
  echo "		return err"
  echo "	}"
  echo "	cSyscalls[name] = *cSyscall"
done
echo '	return nil'
echo '}'

