#!/bin/bash
echo '// generated by ./scripts/get_syscall_table.sh'
echo 'package straceback'
echo
echo 'func init() {'
echo '  syscallNames = make(map[int]string)'
grep NR /usr/include/asm/unistd_64.h | sed 's/^#define __NR_//' | \
while read NAME NR ; do
  echo "  syscallNames[$NR] = \"$NAME\""
done
echo '}'

