#!/bin/bash

set -euo pipefail

if [[ "${#}" -ne 1 ]]; then
    echo 'expected a name of an output file'
    exit 1
fi

# redirect stdout to the file
exec >"${1}"

echo "// Code generated by $(basename ${0}) ${*}; DO NOT EDIT"
echo
echo 'package straceback'
echo
echo 'func init() {'
echo -e '\tsyscallNames = make(map[int]string)'
grep NR /usr/include/asm/unistd_64.h | sed 's/^#define __NR_//' | \
while read NAME NR ; do
  echo -e "\tsyscallNames[$NR] = \"$NAME\""
done
echo '}'
