name: Compile traceloop
on:
  push:
  schedule:
    - cron: '0 2 * * *' # Night builds at 02:00

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@v1

    - name: Build traceloop
      run: |
        make ci

    - name: Build container and publish to Registry
      id: publish-registry
      uses: elgohr/Publish-Docker-Github-Action@2.8
      with:
        name: docker.io/kinvolk/traceloop
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: .
        dockerfile: traceloop.Dockerfile
        snapshot: true
        cache: ${{ github.event_name != 'schedule' }}
